export enum TransactionalEmail {
  REGISTER_PRODUCER = "REGISTER_PRODUCER",
  REGISTER_USER = "REGISTER_USER",
  RESET_PASSWORD = "RESET_PASSWORD",
  SINGLE_PAID_ADQUIRED = "SINGLE_PAID_ADQUIRED",
  SINGLE_PAID_ADQUIRED_WITH_TRANSMISION = "SINGLE_PAID_ADQUIRED_WITH_TRANSMISION",
  MULTIPLE_PAID_ADQUIRED = "MULTIPLE_PAID_ADQUIRED",
  SINGLE_FREE_ADQUIRED = "SINGLE_FREE_ADQUIRED",
  SINGLE_FREE_ADQUIRED_WITH_TRANSMISION = "SINGLE_FREE_ADQUIRED_WITH_TRANSMISION",
  MULTIPLE_FREE_ADQUIRED = "MULTIPLE_FREE_ADQUIRED",
  TICKET_TRANSFERED = "TICKET_TRANSFERED",
  TICKET_SENDED = "TICKET_SENDED",
  REMEMBER = "REMEMBER",
  TICKET_ACTIVATION = "TICKET_ACTIVATION"
}